/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./templates/index.html'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-secondary-container': '#572000',
        'on-tertiary-container': '#006f7f',
        'surface-dim': '#131313',
        'tertiary': '#ffffff',
        'outline': '#8e9379',
        'error': '#ffb4ab',
        'secondary-fixed': '#ffdbcc',
        'on-secondary': '#561f00',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#3c4d00',
        'on-tertiary-fixed': '#001f25',
        'inverse-surface': '#e5e2e1',
        'on-surface-variant': '#c4c9ac',
        'surface-container': '#201f1f',
        'tertiary-fixed': '#a5eeff',
        'background': '#131313',
        'surface-bright': '#393939',
        'on-primary-container': '#556d00',
        'surface-container-high': '#2a2a2a',
        'tertiary-fixed-dim': '#00daf8',
        'error-container': '#93000a',
        'tertiary-container': '#a5eeff',
        'on-primary': '#283500',
        'primary-fixed': '#c3f400',
        'primary-fixed-dim': '#abd600',
        'secondary-container': '#fe6b00',
        'on-secondary-fixed': '#351000',
        'surface-tint': '#abd600',
        'on-primary-fixed': '#161e00',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004e5a',
        'surface-variant': '#353534',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#506600',
        'primary-container': '#c3f400',
        'on-background': '#e5e2e1',
        'secondary': '#ffb693',
        'surface': '#131313',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#7a3000',
        'on-tertiary': '#00363f',
        'surface-container-highest': '#353534',
        'surface-container-low': '#1c1b1b',
        'secondary-fixed-dim': '#ffb693',
        'primary': '#ffffff',
        'outline-variant': '#444933',
        'line-green': '#06C755'
      },
      spacing: {
        'unit-4': '16px',
        'unit-2': '8px',
        'margin-desktop': '48px',
        'unit-1': '4px',
        'unit-16': '64px',
        'gutter': '24px',
        'unit-8': '32px',
        'unit-12': '48px',
        'unit-6': '24px',
        'base': '4px',
        'margin-mobile': '16px'
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'Noto Sans TC', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'Noto Sans TC', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Anybody', 'Noto Sans TC', 'sans-serif'],
        'headline-md': ['Anybody', 'Noto Sans TC', 'sans-serif'],
        'headline-lg': ['Anybody', 'Noto Sans TC', 'sans-serif']
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }]
      }
    }
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')]
};
